version: "3.3"

services:
  mongo:
    container_name: mongo
    image: mongo:4.4
    restart: always
    environment: 
      TZ: "America/Mexico_City"
      MONGO_INITDB_ROOT_USERNAME: "devuser"
      MONGO_INITDB_ROOT_PASSWORD: "devpassword"
    volumes:
      - ./mongodata:/data/db
    ports: 
      - 27017:27017
  emqx:
    container_name: emqx
    image: emqx/emqx:4.2.3
    restart: always
    ports:
      - 18083:18083
      - 18084:18084
      - 1883:1883
      - 8083:8083
      - 8084:8084
      - 8085:8081

    links: 
      - mongo

    environment: 
      EMQX_NAME: ioticos-gl
      EMQX_HOST: 127.0.0.1
      TZ: "America/Mexico_City"

      EMQX_DASHBOARD__DEFAULT_USER__PASSWORD: "emqxdashpass"

      EMQX_ALLOW_ANONYMOUS: "false"
      EMQX_NOMATCH: "deny"

      #mongo conexiones

      EMQX_AUTH__MONGO__TYPE: single
      EMQX_AUTH__MONGO__SERVER: "mongo:27017"
      EMQX_AUTH__MONGO__POOL: 8

      EMQX_AUTH__MONGO__LOGIN: "devuser"
      EMQX_AUTH__MONGO__PASSWORD: "devpassword"
      EMQX_AUTH__MONGO__AUTH_SOURCE: admin

      EMQX_AUTH__MONGO__DATABASE: "iotgl"
      EMQX_AUTH__MONGO__AUTH_QUERY__COLLECTION: "emqxauthrules"

      #super usuarios
      EMQX_AUTH__MONGO__SUPER_QUERY__COLLECTION: "emqxauthrules"
      EMQX_AUTH__MONGO__SUPER_QUERY__SUPER_FIELD: "is_superuser"
      EMQX_AUTH__MONGO__SUPER_QUERY__SELECTOR: "username=%u"
      #queda apagado se explica en el video 70
      EMQX_AUTH__MONGO_SUPER_QUERY: "off"

      #usuario normal video70
      EMQX_AUTH__MONGO__AUTH_QUERY__PASSWORD_HASH: plain
      EMQX_AUTH__MONGO__AUTH_QUERY__PASSWORD_FIELD: "password"
      EMQX_AUTH__MONGO__AUTH_QUERY__SELECTOR: "username=%u"

      EMQX_AUTH__MONGO__ACL_QUERY: "on"
      EMQX_AUTH__MONGO__ACL_QUERY__COLLECTION: "emqxauthrules"
      EMQX_AUTH__MONGO__ACL_QUERY__SELECTOR: "username=%u"

      EMQX_LOADED_PLUGINS: "emqx_recon,emqx_retainer,emqx_management,emqx_dashboard,emqx_auth_mongo"

      EMQX_LISTENER__TCP__EXTERNAL__MAX_CONNECTIONS: 1000
      