version: "3.3"

services:
  mongo:
    container_name: mongo
    image: mongo:4.4
    restart: always
    environment: 
      TZ: "America/Mexico_City"
      MONGO_INITDB_ROOT_USERNAME: "devuser"
      MONGO_INITDB_ROOT_PASSWORD: "devpassword"
    volumes:
      - ./mongodata:/data/db
    ports: 
      - 27017:27017
  emqx:
    container_name: emqx
    image: emqx/emqx:4.2.3
    restart: always
    ports:
      - 18083:18083
      - 8083:8083

    environment: 
      EMQX_NAME: ioticos-gl
      EMQX_HOST: 127.0.0.1
      TZ: "America/Mexico_City"

      EMQX_DASHBOARD__DEFAULT_USER__PASSWORD: "emqxdashpass"

      EMQX_LISTENER__TCP__EXTERNAL__MAX_CONNECTIONS: 1000
      